### ISSUE TITLE
about <template>

### ISSUE THREAD

**Issue by hellodword** [wabarc/obelisk#2]
Continue the issue https://github.com/wabarc/rivet/issues/4 here.

I debug it again, maybe the reason of slow loading is the image size, or, the length of the base64 data URIs.

I generated a archived html with https://github.com/wabarc/rivet/commit/34a2e64411954b8f998266c32f5a70599cc1e86f again and replaced the src of img in the template to 

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAABl0lEQVR4Ae3XP0hVcRjH4UexCDJcImmpTYXGkKKhIopoCIcGiaCiPzS0BkFD1NAaQWBS0KRNwVUJG6IpaGhprKWgpaUwSy266n3bojw/9PwLDO7nu50zPHDgHY5266p+E76Jips3ZUCiPl9ETZtNEY9FjZuUaaZWYE6mJVHrMi3/Z0AbWDDmsjNueS+EsGyuKPDUV5HchF4AG4364I5BM0WB3fYmr7uh08o6jFssCnRjl3crnv7QK9tBF1xfHWhlgK2gx8O/3j2RbkizKHAUwKDG70sfkeqUJVEUGPdn25x13wu3pRoTxYEFh+Rtugyw03Eb5OttGWC/vG22VAYYk7fDogwQTsvX3TxAJNYyYru12uRTWeCnEw7osHqXRFkgXLVWW3ysAjQNWb0HogoQWh45oke6c6IEkNkb+6Q6abEq8N20YV2ydbqhJcoDzx3Tr0u6PV4JUQUIn920w8q6DXsmRAkgsZbX7rnivIuuGfVSU4jqQImtf6ANzP/rH5CpWoGGTANmRU2b0UeKmDRXw8dp6NNuHfULAS/gIhk6B9YAAAAASUVORK5CYII=`, 

then it loaded very fast even it has `<html>` `<head>` stuff.

**Comment by hellodword** [comment]
But I think you're right, we need a method which is similar to `processHTML` but would not add any nodes with <template>.

**Comment by hellodword** [comment]
And we also can consider this issue as a performance issue.

Maybe we could find a way to enhance the performance of very long data URIs.

**Comment by hellodword** [comment]
As I know, Data URLs could not use gzip with other type.

So maybe we can add some minify options:

- minify js/css/html as a [minifier](https://www.npmjs.com/search?q=minifier) 
- reduce img size: 
   - compress
   - resize if the `<img>` target a size

What do you think about this?

**Comment by hellodword** [comment]
Or we can use js to delay the loading of long Data URLs.

**Comment by waybackarchiver** [comment]
> As I know, Data URLs could not use gzip with other type.
> 
> So maybe we can add some minify options:
> 
> * minify js/css/html as a [minifier](https://www.npmjs.com/search?q=minifier)
> * reduce img size:
>   
>   * compress
>   * resize if the `<img>` target a size
> 
> What do you think about this?

I agree providing the option to compress page resources is a good idea, and we may include it as one of the post-optimization options.

In the version of single-file, the original HTML content is replaced, and all resources in the single file are base64 encoded. This option does not cause slow loading and, I guess it is possible. There is slow loading when wrapping the resources into a directory, and I would prefer to find another better solution to handle this case.

Or , we can implement the single-file version first.

**Comment by waybackarchiver** [comment]
Take a step forward to [go-shiori/obelisk](https://github.com/go-shiori/obelisk/issues)
